### ISSUE TITLE
key-holder/member "definieren"

### ISSUE THREAD

**Issue by hornig** [shackspace/hausordnung#1]
key-holder/member "definieren"

**Comment by hdznrrd** [comment]
Vorschlag:

Keymember: Mitglied welches durch andere Keymember berechtigt wurde jederzeit alleinigen Zugang zum Space zu bekommen. Üblicherweise gekennzeichnet durch Hinterlegen eines entsprechenden Schlüssels im Portalsystem.
Keyholder: Mitglieder welches als letztes den Space aufgeschlossen hat. Status bleibt bestehen bis ein anderes Mitglied zum Keyholder wird oder der Space geschlossen wird.
